name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run semantic release
        uses: cycjimmy/semantic-release-action@v6
        with:
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}

      - name: Get new version
        id: get_version
        run: |
          VERSION=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Update Chart.yaml
        run: |
          sed -i "s/^version:.*/version: $VERSION/" charts/aspire-dashboard/Chart.yaml
          git add charts/aspire-dashboard/Chart.yaml
      - name: Install Helm Docs
        uses: gabe565/setup-helm-docs-action@v1

      - name: Run Helm Docs
        run: helm-docs
        
      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Install Dependency Repositories
        run: |
          helm repo add opentelemetry-collector https://open-telemetry.github.io/opentelemetry-helm-charts

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.ACCESS_GITHUB_TOKEN }}"
          skip_existing: true

      - name: Commit changes
        run: |
          if git diff --cached --quiet; then
              echo "No changes to commit."
          else
              git commit -m "chore: update Chart.yaml and documentation for version $VERSION [skip ci]"
              git push origin main
          fi
